"""What Python is handed when pRoloc sends an object back.

There is no exchange format and no grassp reader: ``grasspio::grassp_write_msnset()`` writes an
ordinary h5ad and :func:`anndata.read_h5ad` opens it. So the thing worth testing is not code in
this package -- it is whether the **artifact** is right, which is why every assertion here runs
against ``fixtures/proloc_results.h5ad``, generated by the real R writer
(``fixtures/make_proloc_fixture.R``) rather than hand-authored in Python.

These are regression tests above all. A mistake in the R half does not raise on this side; it
arrives as an object-dtype column where a Categorical was, a re-sorted level set, a compartment
called "NA", or a DataFrame where an embedding was.
"""

from pathlib import Path

import anndata
import numpy as np
import pandas as pd
import pytest

from grassp.io import read
from grassp.util import layer_names

FIXTURE = Path(__file__).parent / "fixtures" / "proloc_results.h5ad"

#: Every column the fixture's MSnSet carried on the feature axis, in pRoloc's own names.
EXPECTED_OBS = {
    "markers",
    "markers.orig",
    "svm",
    "svm.scores",
    "svm.pred",
    "tagm.map.allocation",
    "tagm.map.probability",
    "tagm.map.outlier",
    "pd",
    "Gene names",
    "Topological domain",
    "compartment",
}


@pytest.fixture(scope="module")
def artifact() -> anndata.AnnData:
    if not FIXTURE.exists():  # pragma: no cover - the fixture is committed
        pytest.skip(f"{FIXTURE.name} is missing; regenerate it with make_proloc_fixture.R")
    return anndata.read_h5ad(FIXTURE)


# ==============================================================================
# Structure: an ordinary h5ad, in grassp's orientation
# ==============================================================================


class TestShape:
    def test_opens_with_plain_anndata(self, artifact):
        """No grassp function is involved in reading a pRoloc result."""
        assert isinstance(artifact, anndata.AnnData)

    def test_proteins_are_in_obs(self, artifact):
        """MSnSet's exprs is already features-by-fractions, so nothing is transposed."""
        assert artifact.n_obs == 12
        assert artifact.n_vars == 6
        assert list(artifact.obs_names[:2]) == ["P000", "P001"]
        assert list(artifact.var_names[:1]) == ["Fraction 1"]

    def test_profiles_survive_intact(self, artifact):
        assert np.allclose(np.asarray(artifact.X).sum(axis=1), 1.0, atol=1e-3)

    def test_every_fdata_column_arrives_under_its_own_name(self, artifact):
        """Nothing is renamed, so what you see here is what fvarLabels(x) showed in R."""
        assert set(artifact.obs.columns) == EXPECTED_OBS

    def test_extra_assay_elements_arrive_as_layers(self, artifact):
        # layer_names(), not .layers: anndata >= 0.13 backs .X with layers[None], so iterating
        # the mapping directly reports a phantom layer that is really the main matrix.
        assert set(layer_names(artifact)) == {"pvals"}
        assert artifact.layers["pvals"].shape == artifact.shape

    def test_the_processing_log_comes_along(self, artifact):
        assert "processing" in artifact.uns


# ==============================================================================
# Missing values in text columns
# ==============================================================================


class TestMissingValues:
    """anndataR has no nullable-string encoding: it writes a character ``NA`` as the literal two
    characters ``"NA"``, which would arrive as a compartment called "NA". ``grasspio`` therefore
    writes any ``NA``-carrying text column as a factor, whose missing value survives as an h5ad
    categorical with a ``-1`` code.
    """

    def test_no_column_contains_the_string_NA(self, artifact):
        """The sweeping version of the check, over both axes."""
        for frame in (artifact.obs, artifact.var):
            for column in frame.columns:
                values = set(frame[column].dropna().astype(object).astype(str))
                assert "NA" not in values, f"{column} carries the string 'NA'"

    def test_a_missing_gene_name_is_missing(self, artifact):
        assert pd.isna(artifact.obs["Gene names"].iloc[0])
        assert "NA" not in list(artifact.obs["Gene names"].cat.categories)

    def test_the_sample_axis_gets_the_same_treatment(self, artifact):
        """pData used to be skipped, so an NA there arrived as the string "NA"."""
        condition = artifact.var["condition"]
        assert pd.isna(condition.iloc[1])
        assert set(condition.dropna()) == {"treated", "control"}


# ==============================================================================
# Dtypes: a factor has to arrive as a Categorical, with its levels in order
# ==============================================================================


class TestCategoricalDtype:
    def test_a_factor_arrives_as_a_categorical(self, artifact):
        assert isinstance(artifact.obs["compartment"].dtype, pd.CategoricalDtype)

    def test_level_order_is_the_one_R_had(self, artifact):
        """Not alphabetical, which is what a naive character round trip would produce."""
        assert list(artifact.obs["compartment"].cat.categories) == [
            "Nucleus",
            "Cytosol",
            "Golgi Apparatus",
            "Peroxisome",
        ]

    def test_orderedness_survives(self, artifact):
        assert artifact.obs["compartment"].cat.ordered

    def test_a_declared_but_empty_level_is_not_dropped(self, artifact):
        """ "Peroxisome" has no members. droplevels() in R would have taken it."""
        assert "Peroxisome" in list(artifact.obs["compartment"].cat.categories)
        assert (artifact.obs["compartment"] == "Peroxisome").sum() == 0


# ==============================================================================
# The "unknown" sentinel, which the R side owns in both directions
# ==============================================================================


class TestUnknownSentinel:
    """pRoloc encodes unlabelled features as the literal string ``"unknown"``; grassp uses
    ``NaN``, and its annotators select markers with ``.notna()``, so an untranslated sentinel
    would be trained on as a real compartment.
    """

    @pytest.mark.parametrize("column", ["markers", "markers.orig", "svm.pred", "pd"])
    def test_the_sentinel_is_gone_from_every_text_column(self, artifact, column):
        """Every one, not a nominated marker column: `fcol` is a per-call argument in pRoloc, so
        one MSnSet legitimately carries several marker sets at once."""
        assert "unknown" not in set(artifact.obs[column].dropna())
        assert "unknown" not in list(artifact.obs[column].cat.categories)

    def test_the_unlabelled_features_are_NaN(self, artifact):
        assert artifact.obs["markers"].isna().sum() == 6

    def test_the_labelled_ones_keep_their_compartment(self, artifact):
        assert artifact.obs["markers"].iloc[0] == "Cytosol"
        assert artifact.obs["markers"].notna().sum() == 6

    def test_phenodisco_classes_are_not_special_cased(self, artifact):
        assert {"Phenotype 1", "Phenotype 2"} <= set(artifact.obs["pd"].dropna())


# ==============================================================================
# Matrix-valued fData/pData columns
# ==============================================================================


class TestMatrixColumns:
    """pRoloc stores per-protein by per-compartment values *inside a single* ``fData`` column,
    which is what ``obsm`` is for. They travel as data frames, so the class names come with the
    numbers instead of in a side table.
    """

    def test_a_score_matrix_names_its_own_columns(self, artifact):
        scores = artifact.obsm["svm.all.scores"]
        assert isinstance(scores, pd.DataFrame)
        assert list(scores.columns) == [
            f"{cls}.svm.scores"
            for cls in (
                "Cytosol",
                "Endoplasmic Reticulum",
                "Golgi Apparatus",
                "Mitochondrion",
                "Nucleus",
            )
        ]

    def test_it_is_indexed_by_the_proteins(self, artifact):
        assert list(artifact.obsm["svm.all.scores"].index) == list(artifact.obs_names)

    def test_no_side_table_is_needed_for_it(self, artifact):
        assert "obsm_colnames" not in artifact.uns

    def test_the_values_are_probabilities(self, artifact):
        assert np.allclose(artifact.obsm["svm.all.scores"].to_numpy().sum(axis=1), 1.0)

    def test_a_pdata_matrix_column_arrives_in_varm(self, artifact):
        """pData is the same AnnotatedDataFrame class, so it works by the same route."""
        pcs = artifact.varm["PCs"]
        assert isinstance(pcs, pd.DataFrame)
        assert list(pcs.columns) == ["PC1", "PC2"]
        assert list(pcs.index) == list(artifact.var_names)

    def test_an_embedding_stays_an_array(self, artifact):
        """A matrix column with no class names has nothing to carry, and everything downstream
        expects an embedding to be an array rather than a frame of invented names."""
        assert isinstance(artifact.obsm["X_umap"], np.ndarray)
        assert artifact.obsm["X_umap"].shape == (12, 2)

    def test_a_slashed_class_name_falls_back_to_uns_categories(self, artifact):
        """HDF5 reads "/" as a path separator, so such a name cannot be a data-frame column --
        and pRoloc produces them: hyperLOPIT's classes include "Endoplasmic reticulum/Golgi
        apparatus". The names move to grassp's own ``<key>_categories`` convention instead.
        """
        assert isinstance(artifact.obsm["tagm.map.joint"], np.ndarray)
        categories = list(artifact.uns["tagm.map.joint_categories"])
        assert "Endoplasmic reticulum/Golgi apparatus" in categories
        assert len(categories) == artifact.obsm["tagm.map.joint"].shape[1]


# ==============================================================================
# Merging results onto an object you already have
# ==============================================================================


class TestMergingByHand:
    """The pattern the docs recommend now that there is no merge function: copy over the columns
    you want, reindexed onto the target. pRoloc shrinks objects routinely -- ``filterNA``,
    ``markerMSnSet``, plain ``x[i, ]`` -- so the reindex is the load-bearing part.
    """

    @staticmethod
    def _target(artifact, keep=slice(0, 8), extra=("Q999",)):
        names = list(artifact.obs_names[keep]) + list(extra)
        return anndata.AnnData(
            X=np.zeros((len(names), artifact.n_vars)),
            obs=pd.DataFrame(index=pd.Index(names)),
            var=pd.DataFrame(index=artifact.var_names),
        )

    def test_a_column_reindexes_onto_a_different_row_set(self, artifact):
        target = self._target(artifact)
        target.obs["svm.pred"] = artifact.obs["svm.pred"].reindex(target.obs_names)

        assert isinstance(target.obs["svm.pred"].dtype, pd.CategoricalDtype)
        assert target.obs["svm.pred"].iloc[0] == artifact.obs["svm.pred"].iloc[0]
        # the protein the artifact never saw is missing, not silently mislabelled
        assert pd.isna(target.obs["svm.pred"].loc["Q999"])

    def test_a_matrix_reindexes_the_same_way(self, artifact):
        target = self._target(artifact)
        target.obsm["svm.all.scores"] = artifact.obsm["svm.all.scores"].reindex(
            target.obs_names
        )

        scores = target.obsm["svm.all.scores"]
        assert list(scores.columns) == list(artifact.obsm["svm.all.scores"].columns)
        assert scores.loc["Q999"].isna().all()


# ==============================================================================
# The one conversion Python still makes itself
# ==============================================================================


class TestUnknownToNan:
    """:func:`grassp.io.read_prolocdata` parses ``.rda`` files with the pure-Python ``rdata``
    package, so there is no R there to convert the sentinel. Every other path goes through
    ``grasspio``, which converts on its own side of the boundary.
    """

    def test_the_sentinel_becomes_nan(self):
        out = read._unknown_to_nan(pd.Series(["Golgi", "unknown", "ER"]))
        assert out.iloc[0] == "Golgi"
        assert pd.isna(out.iloc[1])
        assert out.iloc[2] == "ER"

    def test_a_categorical_loses_the_category_rather_than_keeping_a_phantom(self):
        """An unused "unknown" category would show up in every legend and colour map."""
        out = read._unknown_to_nan(pd.Series(pd.Categorical(["Golgi", "unknown"])))
        assert list(out.cat.categories) == ["Golgi"]
        assert pd.isna(out.iloc[1])

    def test_a_categorical_without_the_category_is_untouched(self):
        original = pd.Series(pd.Categorical(["Golgi", "ER"]))
        out = read._unknown_to_nan(original)
        assert list(out.cat.categories) == ["ER", "Golgi"]
        assert out.tolist() == original.tolist()

    def test_it_is_idempotent(self):
        once = read._unknown_to_nan(pd.Series(["Golgi", "unknown"]))
        assert read._unknown_to_nan(once).tolist()[0] == "Golgi"

    @pytest.mark.parametrize("values", [[1.0, np.nan, 3.0], [1, 2, 3], [True, False, True]])
    def test_only_text_columns_can_hold_a_text_sentinel(self, values):
        """Putting ``"unknown"`` in a float column would corrupt it."""
        assert not read._is_labelish(pd.Series(values))

    @pytest.mark.parametrize(
        "values",
        [
            pd.Series(["Golgi", None], dtype=object),
            pd.Series(["Golgi", None], dtype="string"),
            pd.Series(pd.Categorical(["Golgi", None])),
        ],
    )
    def test_every_dtype_a_label_column_can_have(self, values):
        assert read._is_labelish(values)
