"""Tests for the grassp <-> pRoloc h5ad round trip in :mod:`grassp.io.proloc`.

Two layers, both R-free:

* A **pure-Python round trip** -- ``write_msnset`` followed by ``read_msnset`` -- which must be
  lossless for every slot the contract documents. ``TestRoundTripIsLossless`` states the
  complete allowlist of what may differ, so a newly lost slot fails there rather than quietly
  widening the gap.
* Assertions against a **golden fixture** (``fixtures/proloc_results.h5ad``), generated by the
  real R writer from an ``MSnSet`` carrying SVM, TAGM-MAP and phenoDisco results. That fixture
  is where the real pRoloc column names, the ``"unknown"`` encoding and the matrix/scalar split
  are pinned down; because R produced it, it cannot drift from what R does.

``read_proloc_results`` -- grafting results onto an object still in memory -- is the
convenience path, and its tests are about what it must *not* disturb.
"""

import warnings

from pathlib import Path

import anndata
import numpy as np
import pandas as pd
import pytest

from grassp.io import _msnset, proloc
from grassp.util import layer_names, set_matrix

FIXTURE = Path(__file__).parent / "fixtures" / "proloc_results.h5ad"

CATEGORIES = [
    "Cytosol",
    "Endoplasmic Reticulum",
    "Golgi Apparatus",
    "Mitochondrion",
    "Nucleus",
]


# ==============================================================================
# Fixtures
# ==============================================================================


def make_adata(n_proteins: int = 24, n_fractions: int = 6, seed: int = 0) -> anndata.AnnData:
    """A grassp-shaped AnnData: proteins in obs, sum-normalised profiles, some markers.

    Deliberately includes the awkward cases: column names R has to mangle, a Categorical with
    a non-alphabetical category order, unlabelled proteins as ``NaN``, a probability matrix
    with a companion categories key, an embedding without one, an extra layer, and a
    neighbour graph.
    """
    rng = np.random.default_rng(seed)
    obs_names = [f"P{i:03d}" for i in range(n_proteins)]
    # reversed category order, so a naive sort() would be detectable
    ordered = list(reversed(CATEGORIES))
    labels = [ordered[i % len(ordered)] if i % 3 == 0 else None for i in range(n_proteins)]

    adata = anndata.AnnData(
        X=rng.dirichlet(np.ones(n_fractions), size=n_proteins),
        obs=pd.DataFrame(
            {
                "markers": pd.Categorical(labels, categories=ordered),
                "Gene names": [f"GENE{i}" for i in range(n_proteins)],
                "Topological domain": [
                    "Lumenal" if i % 4 == 0 else "" for i in range(n_proteins)
                ],
                "n_detected": rng.integers(1, n_fractions + 1, n_proteins),
            },
            index=pd.Index(obs_names),
        ),
        var=pd.DataFrame(
            {"fraction": [f"F{i}" for i in range(n_fractions)]},
            index=pd.Index([f"Fraction {i}" for i in range(n_fractions)]),
        ),
    )
    adata.obsm["svm_probabilities"] = rng.dirichlet(np.ones(len(CATEGORIES)), size=n_proteins)
    adata.uns["svm_categories"] = list(CATEGORIES)
    adata.obsm["X_umap"] = rng.random((n_proteins, 2))
    adata.layers["pvals"] = rng.random((n_proteins, n_fractions))
    adata.obsp["connectivities"] = np.eye(n_proteins)
    adata.uns["markers_colors"] = ["#111111"] * len(ordered)
    adata.uns["title"] = "Synthetic test dataset"
    return adata


@pytest.fixture
def adata():
    return make_adata()


@pytest.fixture
def exported(adata, tmp_path):
    """``adata`` written out. Nothing about a default export warns."""
    return proloc.write_msnset(adata, tmp_path / "experiment.h5ad")


def merge(artifact, target, **kwargs):
    """:func:`read_proloc_results` with the row-mismatch reporting quietened.

    Several fixtures mismatch on purpose -- the golden fixture holds one protein the target
    lacks, and the filtering fixtures drop half of them -- and the tests that are *about* that
    assert on the warning explicitly rather than going through here.
    """
    kwargs.setdefault("on_missing", "ignore")
    kwargs.setdefault("on_extra", "ignore")
    return proloc.read_proloc_results(artifact, target, **kwargs)


# ==============================================================================
# Export
# ==============================================================================


class TestWriteMsnset:
    def test_writes_the_file_and_returns_its_path(self, exported):
        assert exported.exists()
        assert exported.name == "experiment.h5ad"

    def test_column_names_cross_verbatim(self, adata, exported):
        """pRoloc tolerates non-syntactic fData/pData names, so nothing is mangled.

        Verified against real pRoloc: `svmClassification` runs on an MSnSet whose columns are
        `Gene names` and whose fractions are `Fraction 1`.
        """
        artifact = anndata.read_h5ad(exported)
        assert list(artifact.obs.columns) == list(adata.obs.columns)
        assert list(artifact.var_names) == list(adata.var_names)
        assert "Gene names" in artifact.obs.columns
        assert "Topological domain" in artifact.obs.columns

    def test_nan_becomes_the_unknown_sentinel(self, adata, exported):
        """pRoloc needs it: markerMSnSet and unknownMSnSet fail outright on NA."""
        artifact = anndata.read_h5ad(exported)
        n_nan = int(adata.obs["markers"].isna().sum())
        assert int((artifact.obs["markers"] == "unknown").sum()) == n_nan
        assert not artifact.obs["markers"].isna().any()

    def test_every_text_column_is_converted_not_just_one(self, adata, tmp_path):
        """There is no nominated marker column, because pRoloc takes `fcol` per call.

        An MSnSet can carry several marker sets at once, so all of them need the sentinel.
        """
        adata.obs["markers.orig"] = adata.obs["markers"].astype(object)
        adata.obs["pd.markers"] = pd.array(
            ["Cytosol" if i % 4 else None for i in range(adata.n_obs)], dtype="string"
        )
        path = proloc.write_msnset(adata, tmp_path / "multi.h5ad")
        artifact = anndata.read_h5ad(path)
        for column in ["markers", "markers.orig", "pd.markers"]:
            assert not artifact.obs[column].isna().any(), column
            assert "unknown" in set(artifact.obs[column]), column

    def test_numeric_columns_are_not_given_a_string_sentinel(self, adata, tmp_path):
        adata.obs["score"] = [None if i == 0 else 0.5 for i in range(adata.n_obs)]
        path = proloc.write_msnset(adata, tmp_path / "num.h5ad")
        artifact = anndata.read_h5ad(path)
        assert artifact.obs["score"].dtype == "float64"
        assert artifact.obs["score"].isna().sum() == 1

    def test_conversion_can_be_disabled(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "raw.h5ad", nan_to_unknown=False)
        artifact = anndata.read_h5ad(path)
        assert artifact.obs["markers"].isna().any()

    def test_no_marker_column_is_nominated_in_the_spec(self, exported):
        assert not any("fcol" in k for k in anndata.read_h5ad(exported).uns)

    def test_no_transpose(self, adata, exported):
        """MSnSet's exprs is features-by-fractions, which is already grassp's orientation."""
        artifact = anndata.read_h5ad(exported)
        assert artifact.shape == adata.shape
        assert np.allclose(artifact.X, adata.X)

    def test_probability_matrix_is_exported_with_its_names(self, adata, exported):
        artifact = anndata.read_h5ad(exported)
        assert "svm_probabilities" in artifact.obsm
        assert np.allclose(artifact.obsm["svm_probabilities"], adata.obsm["svm_probabilities"])
        assert list(artifact.uns["obsm_colnames"]["svm_probabilities"]) == CATEGORIES

    def test_layers_become_extra_assay_elements(self, adata, exported):
        """An MSnSet's assayData holds any number of equal-dimension matrices.

        Verified against real pRoloc: they subset along with `exprs` under `markerMSnSet`,
        `filterNA` and `[`, which is what makes this safe rather than a side table.
        """
        artifact = anndata.read_h5ad(exported)
        # layer_names(), not set(artifact.layers): anndata >= 0.13 backs .X with layers[None].
        assert set(layer_names(artifact)) == {"pvals"}
        assert np.allclose(artifact.layers["pvals"], adata.layers["pvals"])

    def test_layers_are_no_longer_reported_as_dropped(self, exported):
        artifact = anndata.read_h5ad(exported)
        assert not any(d.startswith("layers:") for d in artifact.uns["msnset_dropped"])

    def test_layers_can_be_restricted(self, adata, tmp_path):
        adata.layers["extra"] = adata.layers["pvals"] * 2
        path = proloc.write_msnset(adata, tmp_path / "sel.h5ad", layers=["extra"])
        artifact = anndata.read_h5ad(path)
        assert set(layer_names(artifact)) == {"extra"}
        assert "layers:pvals" in artifact.uns["msnset_dropped"]

    def test_layers_can_be_suppressed(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "none.h5ad", layers=[])
        artifact = anndata.read_h5ad(path)
        assert layer_names(artifact) == []
        assert "layers:pvals" in artifact.uns["msnset_dropped"]

    def test_unknown_layer_name_raises(self, adata, tmp_path):
        with pytest.raises(KeyError, match="layers not found"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", layers=["nope"])

    def test_the_primary_layer_is_not_duplicated(self, adata, tmp_path):
        """`layer="pvals"` makes it exprs, so it is not also carried as a layer."""
        path = proloc.write_msnset(
            adata, tmp_path / "p.h5ad", layer="pvals", check_normalized=False
        )
        artifact = anndata.read_h5ad(path)
        assert np.allclose(artifact.X, adata.layers["pvals"])
        assert "pvals" not in artifact.layers
        assert any("replaced by layer" in d for d in artifact.uns["msnset_dropped"])

    def test_varm_becomes_matrix_pdata_columns(self, adata, tmp_path):
        """`pData` is the same AnnotatedDataFrame class as `fData`, so `varm` uses the same
        mechanism as `obsm` -- just on the sample axis.

        Verified against real pRoloc: `x[, 1:2]` subsets such a column with the samples.
        """
        adata.varm["PCs"] = np.arange(adata.n_vars * 3, dtype=float).reshape(-1, 3)
        path = proloc.write_msnset(adata, tmp_path / "vm.h5ad")
        artifact = anndata.read_h5ad(path)
        assert np.allclose(artifact.varm["PCs"], adata.varm["PCs"])
        assert list(artifact.uns["varm_colnames"]["PCs"]) == ["V1", "V2", "V3"]
        assert not any(d.startswith("varm:") for d in artifact.uns["msnset_dropped"])

    def test_varm_names_are_used_when_declared(self, adata, tmp_path):
        adata.varm["PCs"] = np.zeros((adata.n_vars, 2))
        adata.uns["varm_colnames"] = {"PCs": ["PC1", "PC2"]}
        path = proloc.write_msnset(adata, tmp_path / "vn.h5ad")
        artifact = anndata.read_h5ad(path)
        assert list(artifact.uns["varm_colnames"]["PCs"]) == ["PC1", "PC2"]

    def test_a_dataframe_names_its_own_columns(self, adata, tmp_path):
        """What grassp's annotators now write: the names ride on the matrix itself."""
        set_matrix(adata, "scores", np.zeros((adata.n_obs, 2)), ["ER", "Golgi"])
        path = proloc.write_msnset(adata, tmp_path / "df.h5ad")
        artifact = anndata.read_h5ad(path)
        assert list(artifact.uns["obsm_colnames"]["scores"]) == ["ER", "Golgi"]

    def test_carried_columns_outrank_a_stale_declaration(self, adata, tmp_path):
        """Nothing can contradict the names stored alongside the numbers."""
        set_matrix(adata, "scores", np.zeros((adata.n_obs, 2)), ["ER", "Golgi"])
        adata.uns["obsm_colnames"] = {"scores": ["wrong", "alsowrong"]}
        path = proloc.write_msnset(adata, tmp_path / "df2.h5ad")
        artifact = anndata.read_h5ad(path)
        assert list(artifact.uns["obsm_colnames"]["scores"]) == ["ER", "Golgi"]

    def test_varm_can_be_restricted(self, adata, tmp_path):
        adata.varm["PCs"] = np.zeros((adata.n_vars, 2))
        adata.varm["other"] = np.zeros((adata.n_vars, 2))
        path = proloc.write_msnset(adata, tmp_path / "vr.h5ad", varm_keys=["PCs"])
        artifact = anndata.read_h5ad(path)
        assert list(artifact.varm) == ["PCs"]
        assert "varm:other" in artifact.uns["msnset_dropped"]

    def test_unknown_varm_key_raises(self, adata, tmp_path):
        with pytest.raises(KeyError, match="varm keys not found"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", varm_keys=["nope"])

    def test_embeddings_cross_too_with_placeholder_names(self, adata, exported):
        """A matrix fData column is safe whatever it holds, so there is no reason to drop it."""
        artifact = anndata.read_h5ad(exported)
        assert np.allclose(artifact.obsm["X_umap"], adata.obsm["X_umap"])
        assert list(artifact.uns["obsm_colnames"]["X_umap"]) == ["V1", "V2"]

    def test_class_names_come_from_the_companion_label_column(self, adata, tmp_path):
        """The case that was silently dropping portal probability matrices.

        `harmonized_annotation_propagated_probabilities` has no `uns[..._categories]`, but
        `obs["harmonized_annotation_propagated"]` is a Categorical of exactly the right width.
        """
        classes = ["Cytosol", "Golgi", "Nucleus"]
        adata.obs["ann"] = pd.Categorical(
            [classes[i % 3] for i in range(adata.n_obs)], categories=classes
        )
        adata.obsm["ann_probabilities"] = np.zeros((adata.n_obs, 3))
        path = proloc.write_msnset(adata, tmp_path / "comp.h5ad")
        artifact = anndata.read_h5ad(path)
        assert list(artifact.uns["obsm_colnames"]["ann_probabilities"]) == classes

    def test_obsm_can_be_restricted(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "om.h5ad", obsm_keys=["X_umap"])
        artifact = anndata.read_h5ad(path)
        assert list(artifact.obsm) == ["X_umap"]
        assert "obsm:svm_probabilities" in artifact.uns["msnset_dropped"]

    def test_only_graphs_are_unexportable(self, exported):
        """`eSet` has no pairwise slot, so `obsp` is the one thing that genuinely cannot go."""
        artifact = anndata.read_h5ad(exported)
        assert list(artifact.uns["msnset_dropped"]) == ["obsp:connectivities"]

    def test_the_unexportable_graph_is_recorded_but_not_warned_about(self, adata, tmp_path):
        """A warning here would fire on every real dataset, so it would only be noise.

        `obsp` is the sole structural impossibility, `gr.pp.neighbors` puts one on almost every
        object, and it is derived from `.X` anyway. `uns["msnset_dropped"]` and
        `list_msnset_results` are where to look.
        """
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            path = proloc.write_msnset(adata, tmp_path / "x.h5ad")
        assert [str(w.message) for w in caught] == []
        assert list(anndata.read_h5ad(path).uns["msnset_dropped"]) == ["obsp:connectivities"]

    def test_spec_block_is_written(self, exported):
        artifact = anndata.read_h5ad(exported)
        assert artifact.uns["msnset_spec"] == _msnset.SPEC_VERSION
        assert artifact.uns["msnset_exprs_layer"] == ""

    def test_uns_crosses_wholesale(self, adata, tmp_path):
        """No whitelist: h5ad holds arbitrary `uns` and the R side ignores what it cannot use.

        The filter this replaced cost six keys on a real dataset -- `neighbors`, `pca`, `umap`,
        `schema_version` and friends -- for no benefit.
        """
        adata.uns["neighbors"] = {"params": {"n_neighbors": 15, "metric": "euclidean"}}
        adata.uns["pca"] = {"variance_ratio": np.array([0.7, 0.2])}
        adata.uns["schema_version"] = "0.3.0"
        artifact = anndata.read_h5ad(proloc.write_msnset(adata, tmp_path / "u.h5ad"))
        assert set(adata.uns) <= set(artifact.uns)
        assert list(artifact.uns["markers_colors"]) == ["#111111"] * len(CATEGORIES)
        assert artifact.uns["title"] == "Synthetic test dataset"
        assert artifact.uns["schema_version"] == "0.3.0"
        assert artifact.uns["neighbors"]["params"]["n_neighbors"] == 15
        assert np.allclose(artifact.uns["pca"]["variance_ratio"], [0.7, 0.2])

    def test_the_contracts_own_uns_keys_are_regenerated_not_copied(self, adata, tmp_path):
        """An object that came back from R carries a spec block; the export must not inherit it.

        Otherwise a re-export would advertise a stale contract version and a stale drop list.
        """
        adata.uns["msnset_spec"] = "grassp-msnset/99"
        adata.uns["msnset_dropped"] = ["something from last time"]
        adata.uns["obsm_colnames"] = {"no_longer_here": ["a", "b"]}
        artifact = anndata.read_h5ad(proloc.write_msnset(adata, tmp_path / "r.h5ad"))
        assert artifact.uns["msnset_spec"] == _msnset.SPEC_VERSION
        assert list(artifact.uns["msnset_dropped"]) == ["obsp:connectivities"]
        assert set(artifact.uns["obsm_colnames"]) == {"svm_probabilities", "X_umap"}

    def test_explicit_layer_is_used_and_recorded(self, adata, tmp_path):
        path = proloc.write_msnset(
            adata, tmp_path / "l.h5ad", layer="pvals", check_normalized=False
        )
        artifact = anndata.read_h5ad(path)
        assert np.allclose(artifact.X, adata.layers["pvals"])
        assert artifact.uns["msnset_exprs_layer"] == "pvals"

    def test_explicit_obsm_keys_are_honoured(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "o.h5ad", obsm_keys=["X_umap"])
        artifact = anndata.read_h5ad(path)
        assert "X_umap" in artifact.obsm
        assert "svm_probabilities" not in artifact.obsm

    def test_r_script_is_rendered(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "s.h5ad", write_script=True)
        script = path.with_name("s_run_proloc.R")
        text = script.read_text()
        assert "grasspio" in text
        assert "grassp_as_msnset" in text
        assert path.name in text
        assert "grassp_write_msnset" in text


class TestWriteValidation:
    """Fail fast, and name both the problem and the fix."""

    def test_duplicate_obs_names_raise(self, adata, tmp_path):
        adata.obs_names = ["dup"] * adata.n_obs
        with pytest.raises(ValueError, match="obs_names_make_unique"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad")

    def test_blank_obs_names_raise(self, adata, tmp_path):
        names = list(adata.obs_names)
        names[0] = ""
        adata.obs_names = names
        with pytest.raises(ValueError, match="blank or NaN-like"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad")

    def test_missing_layer_raises(self, adata, tmp_path):
        with pytest.raises(KeyError, match="not in data.layers"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", layer="nope")

    def test_missing_obsm_key_raises(self, adata, tmp_path):
        with pytest.raises(KeyError, match="not found in data.obsm"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", obsm_keys=["nope"])

    def test_missing_obs_column_raises(self, adata, tmp_path):
        with pytest.raises(KeyError, match="obs_columns"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", obs_columns=["nope"])

    def test_existing_file_is_not_clobbered(self, adata, tmp_path):
        target = tmp_path / "x.h5ad"
        target.write_text("do not lose me")
        with pytest.raises(ValueError, match="overwrite=True"):
            proloc.write_msnset(adata, target)
        assert target.read_text() == "do not lose me"

    def test_overwrite_is_opt_in(self, adata, tmp_path):
        target = tmp_path / "x.h5ad"
        proloc.write_msnset(adata, target)
        proloc.write_msnset(adata, target, overwrite=True)
        assert target.exists()

    def test_unnormalised_profiles_warn(self, adata, tmp_path):
        adata.X = adata.X * 100.0
        with pytest.warns(UserWarning, match="normalize_total"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad")

    def test_normalisation_check_can_be_silenced(self, adata, tmp_path):
        adata.X = adata.X * 100.0
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            proloc.write_msnset(adata, tmp_path / "x.h5ad", check_normalized=False)
        assert not any("normalize_total" in str(w.message) for w in caught)

    def test_missing_values_warn(self, adata, tmp_path):
        adata.X[0, 0] = np.nan
        with pytest.warns(UserWarning, match="missing values"):
            proloc.write_msnset(adata, tmp_path / "x.h5ad", check_normalized=False)

    def test_unexpected_keyword_is_rejected(self, adata, tmp_path):
        """The CSV fallback is gone; h5ad is the only format."""
        with pytest.raises(TypeError):
            # pylint: disable=unexpected-keyword-arg  (that is what this asserts)
            proloc.write_msnset(adata, tmp_path / "x.h5ad", format="csv")


# ==============================================================================
# Round trip -- the primary workflow
# ==============================================================================


def values_equal(before: pd.Series, after: pd.Series) -> bool:
    """Element-wise equality that counts ``NaN`` in the same place as equal."""
    left, right = before.astype(object), after.astype(object)
    if list(left.isna()) != list(right.isna()):
        return False
    keep = ~left.isna().to_numpy()
    return list(left[keep].astype(str)) == list(right[keep].astype(str))


class TestRoundTripIsLossless:
    """``write_msnset`` then ``read_msnset``, with no R -- the shape of the primary workflow.

    Losslessness is the design goal, so this states the **complete** list of what is allowed to
    differ. Anything newly lost fails here instead of quietly widening the gap.
    """

    @pytest.fixture
    def pair(self, adata, tmp_path):
        """``(original, restored)``, exported with the one value edit turned off.

        ``nan_to_unknown=False`` so the comparison can be exact: with the default, ``NaN``
        leaves as ``"unknown"`` and it is ``grasspio`` that converts back, which no R-free test
        can exercise. The next test pins down that that is the *only* difference.
        """
        adata.varm["PCs"] = np.arange(adata.n_vars * 2, dtype=float).reshape(-1, 2)
        adata.uns["varm_colnames"] = {"PCs": ["PC1", "PC2"]}
        adata.uns["neighbors"] = {"params": {"n_neighbors": 15}}
        adata.layers["imputed"] = adata.X * 2.0
        path = proloc.write_msnset(adata, tmp_path / "rt.h5ad", nan_to_unknown=False)
        return adata, proloc.read_msnset(path, set_colors=False)

    def test_nothing_outside_the_allowlist_is_lost(self, pair):
        """The allowlist is exactly ``obsp``/``varp``, and only because ``eSet`` has no slot."""
        original, restored = pair
        lost = {
            slot: set(getattr(original, slot)) - set(getattr(restored, slot))
            for slot in ("obsm", "varm", "uns", "obsp", "varp")
        }
        lost["layers"] = set(layer_names(original)) - set(layer_names(restored))
        lost["obs"] = set(original.obs.columns) - set(restored.obs.columns)
        lost["var"] = set(original.var.columns) - set(restored.var.columns)
        assert {slot for slot, missing in lost.items() if missing} == {"obsp"}

    def test_x_is_bit_exact(self, pair):
        original, restored = pair
        assert restored.shape == original.shape
        assert np.array_equal(restored.X, original.X)

    def test_obs_values_survive(self, pair):
        original, restored = pair
        for column in original.obs.columns:
            assert values_equal(original.obs[column], restored.obs[column]), column

    def test_obs_dtypes_survive_up_to_anndatas_own_categorisation(self, pair):
        """`AnnData.write_h5ad` calls `strings_to_categoricals()`, so a *repeating* text column
        comes back a Categorical. That is h5ad's behaviour for any AnnData, not the bridge's --
        `Gene names` is all-unique and stays object; `Topological domain` repeats and does not.
        """
        original, restored = pair
        changed = {
            column
            for column in original.obs.columns
            if str(original.obs[column].dtype) != str(restored.obs[column].dtype)
        }
        assert changed == {"Topological domain"}
        assert isinstance(restored.obs["Topological domain"].dtype, pd.CategoricalDtype)
        assert not isinstance(restored.obs["Gene names"].dtype, pd.CategoricalDtype)

    def test_categorical_order_survives(self, pair):
        """`make_adata` reverses the category order, so a stray `sorted()` would show up here."""
        original, restored = pair
        assert list(restored.obs["markers"].cat.categories) == list(
            original.obs["markers"].cat.categories
        )

    def test_var_survives(self, pair):
        original, restored = pair
        assert list(restored.var_names) == list(original.var_names)
        for column in original.var.columns:
            assert values_equal(original.var[column], restored.var[column]), column

    def test_every_obsm_and_varm_matrix_survives_with_its_names(self, pair):
        original, restored = pair
        for key in original.obsm:
            assert np.allclose(restored.obsm[key], original.obsm[key]), key
        for key in original.varm:
            assert np.allclose(restored.varm[key], original.varm[key]), key
        assert list(restored.uns["obsm_colnames"]["svm_probabilities"]) == CATEGORIES
        assert list(restored.uns["varm_colnames"]["PCs"]) == ["PC1", "PC2"]

    def test_every_layer_survives(self, pair):
        original, restored = pair
        assert set(restored.layers) == set(original.layers)
        for key in original.layers:
            assert np.allclose(restored.layers[key], original.layers[key]), key

    def test_nested_uns_survives(self, pair):
        original, restored = pair
        assert restored.uns["neighbors"]["params"]["n_neighbors"] == 15
        assert restored.uns["title"] == original.uns["title"]

    def test_the_default_export_differs_only_by_the_unknown_sentinel(self, adata, tmp_path):
        """With `nan_to_unknown=True` the artifact holds pRoloc's sentinel, and reading it in
        Python does not undo that -- only `grasspio` converts, on its own side of the boundary.
        """
        path = proloc.write_msnset(adata, tmp_path / "d.h5ad")
        restored = proloc.read_msnset(path, set_colors=False)
        assert set(restored.obs["markers"]) - set(adata.obs["markers"].dropna()) == {"unknown"}
        assert not restored.obs["markers"].isna().any()
        assert values_equal(
            adata.obs["markers"].cat.add_categories(["unknown"]).fillna("unknown"),
            restored.obs["markers"],
        )


class TestMergeFidelity:
    """The same fidelity questions, on the convenience path: values and dtypes must survive
    being grafted onto a different object as well as they survive a plain round trip."""

    def test_unlabelled_proteins_are_marked_as_such(self, adata, exported):
        """`NaN` on the way out becomes `"unknown"`, in the same rows."""
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        was_nan = list(adata.obs["markers"].isna())
        is_unknown = [v == "unknown" for v in target.obs["rt_markers"].astype(object)]
        assert is_unknown == was_nan

    def test_marker_labels_survive(self, adata, exported):
        """Labelled proteins keep their exact label; only the unlabelled ones change form.

        The artifact holds pRoloc's `"unknown"`, and reading it back in Python does not undo
        that -- only the R adapter converts on its way out. Faithful, not a bug.
        """
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        original = list(adata.obs["markers"].astype(object))
        restored = list(target.obs["rt_markers"].astype(object))
        assert restored == ["unknown" if pd.isna(v) else v for v in original]

    def test_probability_matrix_survives_exactly(self, adata, exported):
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert np.allclose(
            target.obsm["rt_svm_probabilities"], adata.obsm["svm_probabilities"]
        )

    def test_categories_survive(self, adata, exported):
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert list(target.uns["obsm_colnames"]["rt_svm_probabilities"]) == CATEGORIES

    def test_grafted_matrices_carry_their_categories(self, adata, exported):
        """The uns block is the transport; the landed matrix keeps the names itself."""
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        landed = target.obsm["rt_svm_probabilities"]
        assert isinstance(landed, pd.DataFrame)
        assert list(landed.columns) == CATEGORIES
        assert landed.index.equals(target.obs_names)

    def test_non_syntactic_column_names_survive(self, adata, exported):
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert "rt_Gene names" in target.obs.columns
        assert "rt_Topological domain" in target.obs.columns

    def test_free_text_columns_do_not_become_categoricals(self, adata, exported):
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert not isinstance(target.obs["rt_Gene names"].dtype, pd.CategoricalDtype)

    def test_numeric_columns_stay_numeric(self, adata, exported):
        target = adata.copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert pd.api.types.is_numeric_dtype(target.obs["rt_n_detected"])


class TestMergePreservesTheTarget:
    """The promise of the convenience path: it annotates, and touches nothing else."""

    def test_layers_in_the_artifact_do_not_overwrite_the_target(self, adata, exported):
        """Layers go out, but the merge never brings matrices back.

        `read_proloc_results` promises not to touch `.X` or `.layers`; use `read_msnset` if you
        want the matrices the R side was working with.
        """
        target = adata.copy()
        target.layers["pvals"] = np.zeros_like(target.layers["pvals"])
        before = target.layers["pvals"].copy()
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert np.allclose(target.layers["pvals"], before)

    def test_x_layers_obsp_var_and_varm_are_untouched(self, adata, exported):
        target = adata.copy()
        target.varm["PCs"] = np.zeros((target.n_vars, 2))
        before = {
            "X": target.X.copy(),
            "layer": target.layers["pvals"].copy(),
            "graph": target.obsp["connectivities"].copy(),
            "var": list(target.var.columns),
            "varm": target.varm["PCs"].copy(),
        }
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert np.allclose(target.X, before["X"])
        assert np.allclose(target.layers["pvals"], before["layer"])
        assert np.allclose(target.obsp["connectivities"], before["graph"])
        assert list(target.var.columns) == before["var"]
        assert np.allclose(target.varm["PCs"], before["varm"])

    def test_a_same_named_obsm_entry_is_replaced(self, adata, exported):
        """Not an exception to the promise -- what it writes, it writes under its own name.

        Since an export carries every `.obsm` entry, an unprefixed merge routinely writes back
        over your embeddings. Harmless when the values made the round trip unchanged, which is
        why `key_prefix`/`suffix` exist.
        """
        target = adata.copy()
        target.obsm["X_umap"] = np.zeros_like(target.obsm["X_umap"])
        proloc.read_proloc_results(exported, target)
        assert np.allclose(target.obsm["X_umap"], adata.obsm["X_umap"])
        # ... and prefixing keeps both
        target.obsm["X_umap"] = np.zeros_like(target.obsm["X_umap"])
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert np.allclose(target.obsm["X_umap"], 0.0)
        assert np.allclose(target.obsm["rt_X_umap"], adata.obsm["X_umap"])

    def test_row_order_is_never_changed(self, adata, exported):
        target = adata.copy()
        before = list(target.obs_names)
        proloc.read_proloc_results(exported, target, key_prefix="rt_")
        assert list(target.obs_names) == before

    def test_copy_leaves_the_original_alone(self, adata, exported):
        target = adata.copy()
        before = list(target.obs.columns)
        out = proloc.read_proloc_results(exported, target, key_prefix="rt_", copy=True)
        assert list(target.obs.columns) == before
        assert "rt_markers" in out.obs.columns

    def test_inplace_returns_none(self, adata, exported):
        assert proloc.read_proloc_results(exported, adata.copy()) is None


class TestRowAlignment:
    @pytest.fixture
    def artifact(self, tmp_path):
        adata = make_adata(n_proteins=10, seed=1)
        return proloc.write_msnset(adata, tmp_path / "a.h5ad")

    def test_permuted_order_still_lines_up(self, artifact, tmp_path):
        """Merging is by obs_names, so a reordered target must still be correct."""
        source = anndata.read_h5ad(artifact)
        target = make_adata(n_proteins=10, seed=1)
        target = target[list(reversed(target.obs_names))].copy()
        proloc.read_proloc_results(artifact, target, key_prefix="rt_")
        expected = list(source.obs["markers"].astype(object).reindex(target.obs_names))
        got = list(target.obs["rt_markers"].astype(object))
        assert got == expected

    def test_missing_proteins_become_nan_and_warn(self, artifact):
        target = make_adata(n_proteins=10, seed=1)
        target.obs_names = list(target.obs_names[:8]) + ["ZZZ1", "ZZZ2"]
        with pytest.warns(UserWarning, match="absent from"):
            proloc.read_proloc_results(artifact, target, on_extra="ignore")
        assert target.obs["markers"].isna().sum() >= 2

    def test_extra_proteins_are_dropped_and_warn(self, artifact):
        target = make_adata(n_proteins=6, seed=1)
        with pytest.warns(UserWarning, match="absent from the target"):
            proloc.read_proloc_results(artifact, target, on_missing="ignore")
        assert target.n_obs == 6

    def test_on_missing_error(self, artifact):
        target = make_adata(n_proteins=10, seed=1)
        target.obs_names = list(target.obs_names[:9]) + ["ZZZ1"]
        with pytest.raises(ValueError, match="absent from"):
            proloc.read_proloc_results(artifact, target, on_missing="error", on_extra="ignore")

    def test_on_extra_error(self, artifact):
        target = make_adata(n_proteins=6, seed=1)
        with pytest.raises(ValueError, match="absent from the target"):
            proloc.read_proloc_results(artifact, target, on_extra="error", on_missing="ignore")

    def test_ignore_is_silent(self, artifact):
        target = make_adata(n_proteins=6, seed=1)
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            proloc.read_proloc_results(
                artifact, target, on_missing="ignore", on_extra="ignore"
            )
        assert not any("absent" in str(w.message) for w in caught)

    def test_duplicate_ids_in_the_artifact_raise(self, tmp_path):
        adata = make_adata(n_proteins=4, seed=2)
        path = proloc.write_msnset(adata, tmp_path / "d.h5ad")
        broken = anndata.read_h5ad(path)
        broken.obs_names = ["same"] * broken.n_obs
        with pytest.raises(ValueError, match="duplicated protein IDs"):
            proloc.read_proloc_results(broken, adata)

    def test_id_column_is_used_when_given(self, tmp_path):
        adata = make_adata(n_proteins=5, seed=3)
        path = proloc.write_msnset(adata, tmp_path / "i.h5ad")
        artifact = anndata.read_h5ad(path)
        artifact.obs["altid"] = list(adata.obs_names)
        artifact.obs_names = [f"row{i}" for i in range(artifact.n_obs)]
        proloc.read_proloc_results(artifact, adata, id_column="altid", key_prefix="rt_")
        assert adata.obs["rt_markers"].notna().sum() > 0

    def test_bad_id_column_raises(self, artifact):
        with pytest.raises(KeyError, match="id_column"):
            proloc.read_proloc_results(
                artifact, make_adata(n_proteins=10, seed=1), id_column="nope"
            )


class TestFilteringInProlocChangesDimensions:
    """What happens when the R side filters, so the artifact is a different shape.

    Real pRoloc workflows shrink objects routinely -- ``filterNA``, ``markerMSnSet``,
    ``unknownMSnSet``, ``filterZeroRows``/``filterZeroCols``, plain ``x[i, j]`` subsetting.
    The merge has to stay safe under all of it, because the alternative is a silently
    half-populated annotation that reads like a result.
    """

    @pytest.fixture
    def filtered_artifact(self, adata, tmp_path):
        """An artifact covering only the first half of the proteins and half the fractions."""
        full = proloc.write_msnset(adata, tmp_path / "full.h5ad")
        artifact = anndata.read_h5ad(full)
        keep = artifact.obs_names[: adata.n_obs // 2]
        subset = artifact[keep, artifact.var_names[:3]].copy()
        return subset

    def test_target_keeps_its_own_shape(self, adata, filtered_artifact):
        """The merge annotates; it never resizes the object being merged onto."""
        shape_before = adata.shape
        merge(filtered_artifact, adata, key_prefix="f_")
        assert adata.shape == shape_before

    def test_dropped_proteins_become_nan_not_wrong_labels(self, adata, filtered_artifact):
        n_kept = filtered_artifact.n_obs
        merge(filtered_artifact, adata, key_prefix="f_")
        assert adata.obs["f_markers"].notna().sum() <= n_kept
        # the proteins pRoloc never saw must be NaN, never silently given a neighbour's label
        seen = set(filtered_artifact.obs_names)
        unseen = [n for n in adata.obs_names if n not in seen]
        assert unseen, "the fixture must actually drop some proteins"
        assert adata.obs["f_markers"].reindex(unseen).isna().all()

    def test_dropped_proteins_get_zero_probability_rows(self, adata, filtered_artifact):
        """Zero rather than NaN, so an unmeasured protein carries no evidence.

        A real prediction sums to 1, so an all-zero row is distinguishable -- but note that a
        naive ``argmax`` over the matrix would still return class 0 for those rows. The label
        column is the safe thing to read; it is ``NaN``.
        """
        merge(filtered_artifact, adata, key_prefix="f_")
        matrix = adata.obsm["f_svm_probabilities"]
        assert matrix.shape == (adata.n_obs, len(CATEGORIES))
        zero_rows = int((matrix.sum(axis=1) == 0).sum())
        assert zero_rows == adata.n_obs - filtered_artifact.n_obs

    def test_the_shortfall_is_reported_not_silent(self, adata, filtered_artifact):
        with pytest.warns(UserWarning, match="absent from"):
            proloc.read_proloc_results(filtered_artifact, adata, key_prefix="f_")

    def test_shortfall_can_be_made_fatal(self, adata, filtered_artifact):
        with pytest.raises(ValueError, match="absent from"):
            proloc.read_proloc_results(
                filtered_artifact, adata, on_missing="error", key_prefix="f_"
            )

    def test_provenance_records_the_counts(self, adata, filtered_artifact):
        merge(filtered_artifact, adata, key_prefix="f_")
        params = adata.uns["f_proloc_import"]
        assert params["n_matched"] == filtered_artifact.n_obs
        assert params["n_target"] == adata.n_obs

    def test_dropped_fractions_are_irrelevant_to_the_merge(self, adata, filtered_artifact):
        """Filtering columns in R cannot corrupt the merge, because `.var`/`.X` are not read.

        The score matrices are per-compartment, not per-fraction, so a 3-fraction result
        merges onto a 6-fraction object perfectly well.
        """
        assert filtered_artifact.n_vars < adata.n_vars
        merge(filtered_artifact, adata, key_prefix="f_")
        assert adata.n_vars == 6
        assert "f_svm_probabilities" in adata.obsm


class TestRemapDetection:
    """`pRoloc::remap` replaces exprs with PCA scores and renames fractions to PC1..PCn."""

    def test_pc_named_fractions_warn(self, adata, tmp_path):
        path = proloc.write_msnset(adata, tmp_path / "r.h5ad")
        artifact = anndata.read_h5ad(path)
        artifact.var_names = [f"PC{i + 1}" for i in range(artifact.n_vars)]
        with pytest.warns(UserWarning, match="pRoloc::remap"):
            proloc.read_proloc_results(artifact, adata, key_prefix="r_")

    def test_normal_fractions_do_not_warn(self, adata, exported):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            proloc.read_proloc_results(exported, adata, key_prefix="n_")
        assert not any("remap" in str(w.message) for w in caught)

    def test_annotations_still_merge_when_remapped(self, adata, tmp_path):
        """The warning is advisory: feature annotations are still perfectly valid."""
        path = proloc.write_msnset(adata, tmp_path / "r2.h5ad")
        artifact = anndata.read_h5ad(path)
        artifact.var_names = [f"PC{i + 1}" for i in range(artifact.n_vars)]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")  # the remap advisory; asserted on above
            proloc.read_proloc_results(artifact, adata, key_prefix="r_")
        assert len(adata.obs["r_markers"]) == adata.n_obs
        assert adata.obs["r_markers"].notna().all()


# ==============================================================================
# The golden fixture -- real pRoloc column names
# ==============================================================================


@pytest.fixture
def target_for_fixture():
    """A target matching the fixture, minus its last protein (to exercise `on_extra`)."""
    ids = [f"P{i:03d}" for i in range(11)]
    rng = np.random.default_rng(11)
    adata = anndata.AnnData(
        X=rng.dirichlet(np.ones(6), size=len(ids)),
        obs=pd.DataFrame(index=pd.Index(ids)),
        var=pd.DataFrame(index=pd.Index([f"Fraction.{i}" for i in range(1, 7)])),
    )
    return adata


class TestGoldenFixture:
    """Assertions against a fixture generated by the real R writer.

    ``fixtures/make_proloc_fixture.R`` builds an ``MSnSet`` with the columns pRoloc's SVM,
    TAGM-MAP and phenoDisco produce and runs ``grasspio::grassp_write_msnset()`` on it, so the
    fixture cannot drift from what R actually emits.
    """

    def test_nothing_is_renamed(self):
        """Non-syntactic names survive, because pRoloc tolerates them."""
        inventory = proloc.list_msnset_results(FIXTURE)
        assert inventory["spec"] == _msnset.SPEC_VERSION
        assert "Gene names" in inventory["obs"]
        assert "Topological domain" in inventory["obs"]
        assert not any("." in n for n in ("Gene names", "Topological domain"))

    def test_every_proloc_column_is_present_under_its_own_name(self):
        inventory = proloc.list_msnset_results(FIXTURE)
        for column in [
            "markers",
            "markers.orig",
            "svm",
            "svm.scores",
            "svm.pred",
            "tagm.map.allocation",
            "tagm.map.probability",
            "tagm.map.outlier",
            "pd",
        ]:
            assert column in inventory["obs"], column

    def test_no_marker_column_is_declared(self):
        """Which one is "the" markers is the caller's choice, per pRoloc call."""
        inventory = proloc.list_msnset_results(FIXTURE)
        assert "marker_column" not in inventory
        # but several marker columns are present and equally usable
        assert {"markers", "markers.orig"} <= set(inventory["obs"])

    def test_numeric_columns_stay_numeric(self):
        inventory = proloc.list_msnset_results(FIXTURE)
        assert inventory["obs"]["svm.scores"] == "float64"
        assert inventory["obs"]["tagm.map.outlier"] == "float64"

    def test_matrix_columns_became_obsm_with_their_own_colnames(self):
        """Including pRoloc's `<class>.svm.scores` decoration, kept verbatim."""
        inventory = proloc.list_msnset_results(FIXTURE)
        assert set(inventory["matrices"]) == {"svm.all.scores", "tagm.map.joint"}
        assert inventory["matrices"]["svm.all.scores"]["shape"] == [12, 5]
        assert inventory["matrices"]["svm.all.scores"]["categories"] == [
            f"{c}.svm.scores" for c in CATEGORIES
        ]
        # tagmMapPredict writes plain class names, and those are kept plain
        assert inventory["matrices"]["tagm.map.joint"]["categories"] == CATEGORIES

    def test_the_inventory_covers_the_whole_artifact_not_just_obs(self):
        """The other axis and the extra assay elements are part of the round trip too."""
        inventory = proloc.list_msnset_results(FIXTURE)
        assert inventory["n_obs"] == 12
        assert inventory["n_vars"] == 6
        assert inventory["layers"] == ["pvals"]  # not ["None", "pvals"]
        assert "fraction" in inventory["var"]
        assert inventory["var_matrices"]["PCs"]["shape"] == [6, 2]
        assert inventory["var_matrices"]["PCs"]["categories"] == ["PC1", "PC2"]

    def test_upstream_misnaming_is_reported_as_a_note(self):
        inventory = proloc.list_msnset_results(FIXTURE)
        assert "ksvm" in inventory["notes"]["svm.all.scores"]

    def test_a_method_with_no_score_column_is_fine(self):
        """phenoDisco writes only `pd`; nothing assumes a score or matrix accompanies it."""
        inventory = proloc.list_msnset_results(FIXTURE)
        assert "pd" in inventory["obs"]
        assert not any(key.startswith("pd") for key in inventory["matrices"])

    def test_unknown_already_became_nan_on_the_r_side(self, target_for_fixture):
        """grasspio converts the sentinel on export, so Python has nothing to translate."""
        merge(FIXTURE, target_for_fixture)
        for column in ["markers", "markers.orig", "svm.pred", "pd"]:
            values = target_for_fixture.obs[column]
            assert "unknown" not in set(values.dropna()), column
            assert values.isna().any(), column

    def test_import_writes_every_column_and_matrix(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture)
        for column in [
            "markers",
            "markers.orig",
            "svm",
            "svm.scores",
            "svm.pred",
            "tagm.map.allocation",
            "tagm.map.probability",
            "tagm.map.outlier",
            "pd",
            "Gene names",
            "Topological domain",
        ]:
            assert column in target_for_fixture.obs.columns, column
        for key in ["svm.all.scores", "tagm.map.joint"]:
            assert key in target_for_fixture.obsm, key

    def test_class_names_are_recorded_in_uns(self, target_for_fixture):
        """The only place they can live -- obsm arrays have no column names."""
        merge(FIXTURE, target_for_fixture)
        colnames = target_for_fixture.uns["obsm_colnames"]
        assert colnames["tagm.map.joint"] == CATEGORIES
        assert len(colnames["svm.all.scores"]) == len(CATEGORIES)

    def test_nothing_is_invented(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture)
        invented = [
            k
            for k in list(target_for_fixture.obsm) + list(target_for_fixture.uns)
            if k.endswith(("_probabilities", "_probability", "_categories"))
            and k != "obsm_colnames"
        ]
        assert invented == []

    def test_novel_phenotypes_survive(self, target_for_fixture):
        """phenoDisco invents "Phenotype N" classes grassp has no colour for."""
        merge(FIXTURE, target_for_fixture)
        values = set(target_for_fixture.obs["pd"].dropna())
        assert "Phenotype 1" in values
        assert "Phenotype 2" in values

    def test_colours_are_assigned_where_they_make_sense(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture)
        assert "markers_colors" in target_for_fixture.uns

    def test_matrices_keep_their_rows_aligned(self, target_for_fixture):
        """The fixture's 12th protein is absent from the target and must be dropped."""
        source = anndata.read_h5ad(FIXTURE)
        merge(FIXTURE, target_for_fixture)
        assert target_for_fixture.obsm["tagm.map.joint"].shape == (11, 5)
        assert np.allclose(
            target_for_fixture.obsm["tagm.map.joint"],
            source.obsm["tagm.map.joint"][:11],
        )

    def test_provenance_is_recorded(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture)
        params = target_for_fixture.uns["proloc_import"]
        assert params["source"].endswith("proloc_results.h5ad")
        assert params["spec"] == _msnset.SPEC_VERSION
        assert "svm.pred" in params["obs_columns"]
        assert "svm.all.scores" in params["matrices"]
        assert params["n_matched"] == 11
        assert params["n_artifact"] == 12
        assert "ksvm" in params["notes"]["svm.all.scores"]

    def test_suffix_namespaces_everything(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture, suffix="_control")
        assert "svm.pred_control" in target_for_fixture.obs.columns
        assert "tagm.map.joint_control" in target_for_fixture.obsm

    def test_proloc_vocabulary_is_preserved(self, target_for_fixture):
        merge(FIXTURE, target_for_fixture)
        assert "Endoplasmic Reticulum" in set(target_for_fixture.obs["markers"].dropna())


class TestReadMsnsetOnRealProlocOutput:
    """`read_msnset` on the golden fixture: the return leg of the primary workflow."""

    def test_returns_a_usable_adata(self):
        adata = proloc.read_msnset(FIXTURE)
        assert adata.n_obs == 12
        assert adata.n_vars == 6
        assert "markers" in adata.obs.columns
        assert adata.obs["markers"].isna().sum() == 6

    def test_every_slot_the_msnset_had_comes_back(self):
        """Not just `obs`: the other axis, the extra assay element and the matrix columns."""
        adata = proloc.read_msnset(FIXTURE)
        assert adata.obsm["tagm.map.joint"].shape == (12, 5)
        assert list(adata.uns["obsm_colnames"]["tagm.map.joint"]) == CATEGORIES
        assert adata.varm["PCs"].shape == (6, 2)
        assert list(adata.uns["varm_colnames"]["PCs"]) == ["PC1", "PC2"]
        assert adata.layers["pvals"].shape == (12, 6)
        assert "fraction" in adata.var.columns

    def test_expression_matrix_is_carried_over(self):
        source = anndata.read_h5ad(FIXTURE)
        adata = proloc.read_msnset(FIXTURE)
        assert np.allclose(adata.X, source.X)

    def test_it_is_essentially_read_h5ad(self):
        """Nothing is renamed or converted, so the result matches a plain read."""
        adata = proloc.read_msnset(FIXTURE)
        plain = anndata.read_h5ad(FIXTURE)
        assert list(adata.obs.columns) == list(plain.obs.columns)
        assert list(adata.obsm) == list(plain.obsm)
        assert np.allclose(adata.X, plain.X)

    def test_the_merge_is_a_wrapper_over_it(self):
        """`read_proloc_results` is documented as thin, so the two must agree column for column.

        Same values, same dtypes -- the only difference being which object they land on.
        """
        standalone = proloc.read_msnset(FIXTURE, set_colors=False)
        target = anndata.read_h5ad(FIXTURE)
        target.obs = pd.DataFrame(index=target.obs_names)
        merge(FIXTURE, target, set_colors=False)
        for column in standalone.obs.columns:
            assert values_equal(standalone.obs[column], target.obs[column]), column
            assert str(standalone.obs[column].dtype) == str(target.obs[column].dtype), column
        for key in standalone.obsm:
            assert np.allclose(standalone.obsm[key], target.obsm[key]), key


class TestSpecVersionGuard:
    def test_newer_artifact_raises(self, adata, exported):
        artifact = anndata.read_h5ad(exported)
        artifact.uns["msnset_spec"] = "grassp-msnset/99"
        with pytest.raises(_msnset.SpecVersionError, match="Upgrade grassp"):
            proloc.read_proloc_results(artifact, adata)

    def test_artifact_without_a_spec_is_still_readable(self, adata, exported):
        """A plain pRoloc export has no spec block; heuristics must carry it."""
        artifact = anndata.read_h5ad(exported)
        del artifact.uns["msnset_spec"]
        proloc.read_proloc_results(artifact, adata, key_prefix="rt_")
        assert "rt_markers" in adata.obs.columns

    def test_missing_file_raises(self, adata, tmp_path):
        with pytest.raises(FileNotFoundError):
            proloc.read_proloc_results(tmp_path / "nope.h5ad", adata)
