#!/usr/bin/env Rscript
## Generate `proloc_results.h5ad`, the golden fixture for the pRoloc import path.
##
## Run from the repository root, in an R environment that has grasspio installed:
##
##     Rscript grassp/tests/fixtures/make_proloc_fixture.R
##
## The fixture is what `grasspio::grassp_write_msnset()` actually emits for an `MSnSet`
## carrying the columns pRoloc's SVM, TAGM-MAP and phenoDisco produce. It is generated by the
## real writer rather than hand-authored in Python, so it cannot drift from what R does -- and
## since the Python side now just calls `anndata.read_h5ad()`, this file *is* the contract.
##
## Deliberate features, each of which a test depends on:
##
##   * `markers` uses pRoloc's literal "unknown", which the writer converts to NA on the way
##     out (unknown_to_na = TRUE) -- that conversion belongs on pRoloc's side.
##   * `compartment` is an ordered factor whose levels are deliberately not alphabetical: both
##     the order and the ordered-ness have to survive into pandas.
##   * `Gene names` carries an NA, which must arrive as a real missing value rather than as the
##     two-character string "NA".
##   * `condition` does the same on the pData axis, which is the half that used to be skipped.
##   * `svm.all.scores` is a matrix-valued fData column whose colnames carry pRoloc's
##     `<class>.svm.scores` decoration; it becomes an obsm data frame that names itself.
##   * `tagm.map.joint` has a class name containing "/", as hyperLOPIT's do, which cannot be an
##     HDF5 dataset name -- so it falls back to a plain array plus uns$tagm.map.joint_categories.
##   * `X_umap` is a matrix column with no colnames, standing in for an embedding: it must come
##     back as a plain array, not a data frame of invented names.
##   * `pd` has no companion score column, and invents "Phenotype 1"/"Phenotype 2" classes
##     that grassp has no canonical colour for.
##   * `markers.orig` is a pRolocdata convention the bridge has no special case for.
##   * `Gene names` and `Topological domain` are non-syntactic, which pRoloc tolerates.
##   * a `pvals` assayData element, which becomes an AnnData layer.
##   * a matrix-valued `PCs` pData column, which becomes an AnnData varm entry.

suppressMessages({
  library(grasspio)
  library(Biobase)
})
set.seed(1)

classes <- c(
  "Cytosol", "Endoplasmic Reticulum", "Golgi Apparatus", "Mitochondrion", "Nucleus"
)
proteins <- sprintf("P%03d", 0:11)
fractions <- sprintf("Fraction %d", 1:6)

markers <- c(
  "Cytosol", "Endoplasmic Reticulum", "unknown", "Golgi Apparatus", "unknown",
  "Mitochondrion", "unknown", "Nucleus", "unknown", "unknown",
  "Endoplasmic Reticulum", "unknown"
)
svm <- c(
  "Cytosol", "Endoplasmic Reticulum", "Golgi Apparatus", "Golgi Apparatus",
  "Endoplasmic Reticulum", "Mitochondrion", "Nucleus", "Nucleus", "Cytosol",
  "Endoplasmic Reticulum", "Endoplasmic Reticulum", "Golgi Apparatus"
)
svm_scores <- c(0.98, 0.95, 0.62, 0.88, 0.91, 0.99, 0.55, 0.97, 0.48, 0.79, 0.93, 0.71)
## getPredictions() at t = 0.7 demotes sub-threshold calls, then restores every marker to its
## ground-truth label (pRoloc R/MSnSet.R:184-186).
svm_pred <- ifelse(markers != "unknown", markers,
                   ifelse(svm_scores >= 0.7, svm, "unknown"))
## tagmMapPredict pins markers to probability 1 and outlier 0.
tagm_probability <- ifelse(markers != "unknown", 1.0, svm_scores)
tagm_outlier <- ifelse(markers != "unknown", 0.0, round(0.02 * seq_along(markers), 3))
## phenoDisco keeps marker classes and invents "Phenotype N" for new clusters.
pd <- c(
  "Cytosol", "Endoplasmic Reticulum", "Phenotype 1", "Golgi Apparatus", "Phenotype 1",
  "Mitochondrion", "Phenotype 2", "Nucleus", "unknown", "unknown",
  "Endoplasmic Reticulum", "Phenotype 2"
)

row_stochastic <- function(n, k) {
  m <- matrix(runif(n * k), nrow = n)
  round(m / rowSums(m), 6)
}

exprs_matrix <- row_stochastic(length(proteins), length(fractions))
dimnames(exprs_matrix) <- list(proteins, fractions)

fdata <- data.frame(
  check.names = FALSE,
  markers = markers,
  `markers.orig` = markers,
  svm = svm,
  `svm.scores` = svm_scores,
  `svm.pred` = svm_pred,
  `tagm.map.allocation` = svm,
  `tagm.map.probability` = tagm_probability,
  `tagm.map.outlier` = tagm_outlier,
  pd = pd,
  `Gene names` = c(NA, sprintf("GENE%d", seq_along(proteins)[-1] - 1L)),
  `Topological domain` = ifelse(seq_along(proteins) %% 3 == 1, "Lumenal", ""),
  row.names = proteins,
  stringsAsFactors = FALSE
)

## An ordered factor whose levels are not in alphabetical order, which is what a pandas
## Categorical hands over and what has to survive the trip back.
fdata$compartment <- factor(
  rep(c("Nucleus", "Cytosol", "Golgi Apparatus"), length.out = length(proteins)),
  levels = c("Nucleus", "Cytosol", "Golgi Apparatus", "Peroxisome"),
  ordered = TRUE
)

## Matrix-valued fData columns: pRoloc decorates score-matrix colnames, TAGM's joint plain.
svm_all <- row_stochastic(length(proteins), length(classes))
dimnames(svm_all) <- list(proteins, paste0(classes, ".svm.scores"))
fdata$`svm.all.scores` <- svm_all

## One of TAGM's classes has a "/" in it, as hyperLOPIT's "Endoplasmic reticulum/Golgi
## apparatus" does. HDF5 reads that as a path, so this matrix cannot be written as a data frame.
tagm_classes <- c(classes[-2], "Endoplasmic reticulum/Golgi apparatus")
tagm_joint <- row_stochastic(length(proteins), length(tagm_classes))
dimnames(tagm_joint) <- list(proteins, tagm_classes)
fdata$`tagm.map.joint` <- tagm_joint

## A nameless matrix column, standing in for an embedding grassp put in obsm.
umap <- matrix(round(runif(length(proteins) * 2), 6), nrow = length(proteins))
rownames(umap) <- proteins
fdata$X_umap <- umap

## An extra assayData element, which becomes an AnnData layer.
pvals <- matrix(round(runif(length(proteins) * length(fractions)), 6),
                nrow = length(proteins), dimnames = dimnames(exprs_matrix))

## pData carries scalar columns and a matrix one; the latter becomes an AnnData varm entry.
pdata <- data.frame(
  check.names = FALSE,
  fraction = fractions,
  ## A missing value on the sample axis, which must not arrive in Python as the string "NA".
  condition = c("treated", NA, "control", "treated", NA, "control"),
  row.names = fractions,
  stringsAsFactors = FALSE
)
pdata$PCs <- matrix(round(runif(length(fractions) * 2), 6),
                    nrow = length(fractions),
                    dimnames = list(fractions, c("PC1", "PC2")))

x <- new(
  "MSnSet",
  exprs = exprs_matrix,
  featureData = new("AnnotatedDataFrame", data = fdata),
  phenoData = new("AnnotatedDataFrame", data = pdata)
)
Biobase::assayDataElement(x, "pvals") <- pvals
stopifnot(validObject(x))

out <- "grassp/tests/fixtures/proloc_results.h5ad"
grassp_write_msnset(x, out, overwrite = TRUE)
cat("wrote", out, "-", round(file.info(out)$size / 1024, 1), "kB\n")
